import Foundation

/// クリップボード履歴に「残してよいか」を判定する。
///
/// 設計方針: 迷ったら残さない（fail-closed）。
/// 履歴が1件取りこぼされても実害は小さいが、APIキーや口座番号が平文で溜まると実害が大きい。
public enum ClipDecision: Equatable, Sendable {
    case store
    case skipEmpty
    case skipConcealed(String)          // パスワード管理ソフト等が付ける機密フラグ
    case skipExcludedApp(String)        // 除外指定したアプリからのコピー
    case skipSecret(SecretKind)         // 中身が秘密情報に見える
    case skipTooLarge(Int)
    case skipTooMany(Int)               // ファイルの本数が多すぎる
    case skipTypeDisabled(String)       // 設定でその種類を残さないことにしている
    case skipDuplicate

    public var isStored: Bool { self == .store }

    /// 画面やログに出す説明（中身そのものは絶対に含めない）
    public var reason: String {
        switch self {
        case .store: return "保存"
        case .skipEmpty: return "空のため保存しない"
        case .skipConcealed(let t): return "機密フラグ付きのため保存しない（\(t)）"
        case .skipExcludedApp(let b): return "除外アプリのため保存しない（\(b)）"
        case .skipSecret(let k): return "秘密情報を検知したため保存しない（\(k.label)）"
        case .skipTooLarge(let n): return "大きすぎるため保存しない（\(ByteSize.label(n))）"
        case .skipTooMany(let n): return "本数が多すぎるため保存しない（\(n)件）"
        case .skipTypeDisabled(let t): return "設定で\(t)を残さないことにしています"
        case .skipDuplicate: return "直前と同じため保存しない"
        }
    }
}

/// 拾ったものの中身。
///
/// 画像は「大きさと指紋」だけをここに入れる。絵そのものを判定に渡さないのは、
/// 判定側が中身を持たない（持てば、捨てると決めたものまで一度メモリに写ることになる）ため。
public enum ClipPayload: Equatable, Sendable {
    case text(String)
    case image(byteCount: Int, fingerprint: String)
    case files([String])

    public var kind: ClipKind {
        switch self {
        case .text: return .text
        case .image: return .image
        case .files: return .file
        }
    }
}

public enum SecretKind: Equatable, Sendable {
    case apiKey(String)
    case privateKey
    case jwt
    case creditCard
    case myNumber
    case userPattern(String)

    public var label: String {
        switch self {
        case .apiKey(let name): return "APIキーらしき文字列: \(name)"
        case .privateKey: return "秘密鍵"
        case .jwt: return "JWTトークン"
        case .creditCard: return "カード番号らしき数字列"
        case .myNumber: return "マイナンバーらしき数字列"
        case .userPattern(let p): return "指定した除外語: \(p)"
        }
    }
}

public struct ClipboardGuard: Sendable {

    /// 他アプリが「これは履歴に残すな」と宣言するために付けるペーストボード型。
    /// 1Password や多くのパスワード管理ソフトが対応している事実上の共通規約。
    public static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
    ]

    /// 既定の除外アプリ。ここからのコピーは中身を見ずに捨てる。
    public static let defaultExcludedBundleIDs: Set<String> = [
        "com.1password.1password",
        "com.agilebits.onepassword",
        "com.agilebits.onepassword7",
        "com.apple.keychainaccess",
        "com.bitwarden.desktop",
        "com.lastpass.LastPass",
        "in.sinew.Enpass-Desktop",
        "com.dashlane.dashlanephonefinal",
        "com.apple.Passwords",
    ]

    /// 一度に覚えるファイルの本数の上限。
    /// フォルダを丸ごと選んでコピーされたときに、履歴が1件で数千行にならないようにする。
    public static let maxFileCount = 50

    public var excludedBundleIDs: Set<String>
    public var userPatterns: [String]
    public var maxBytes: Int
    public var capturesImages: Bool
    public var capturesFiles: Bool
    public var maxImageBytes: Int

    public init(
        excludedBundleIDs: Set<String> = ClipboardGuard.defaultExcludedBundleIDs,
        userPatterns: [String] = [],
        maxBytes: Int = 1_000_000,
        capturesImages: Bool = true,
        capturesFiles: Bool = true,
        maxImageBytes: Int = 12 * 1024 * 1024
    ) {
        self.excludedBundleIDs = excludedBundleIDs
        self.userPatterns = userPatterns
        self.maxBytes = maxBytes
        self.capturesImages = capturesImages
        self.capturesFiles = capturesFiles
        self.maxImageBytes = maxImageBytes
    }

    // MARK: - 種類ごとの判定

    /// 文字・画像・ファイルをまとめて判定する入口。
    ///
    /// ⚠️ 文字のときは、下の decide(types:sourceBundleID:text:byteCount:previousText:) に
    /// そのまま渡している。判定の**順番**（空 → 大きさ → 重複 → 除外語 → 秘密検知）が
    /// 変わると今までの結果が変わってしまうので、文字だけは元の道をそのまま通す。
    public func decide(
        payload: ClipPayload,
        types: [String],
        sourceBundleID: String?,
        previous: ClipPayload?
    ) -> ClipDecision {
        switch payload {
        case .text(let text):
            var previousText: String?
            if case .text(let p)? = previous { previousText = p }
            return decide(
                types: types,
                sourceBundleID: sourceBundleID,
                text: text,
                byteCount: text.utf8.count,
                previousText: previousText
            )

        case .image(let byteCount, let fingerprint):
            if let blocked = blockedBySource(types: types, sourceBundleID: sourceBundleID) { return blocked }
            guard capturesImages else { return .skipTypeDisabled("画像") }
            guard byteCount > 0 else { return .skipEmpty }
            if byteCount > maxImageBytes { return .skipTooLarge(byteCount) }
            if case .image(_, let previousFingerprint)? = previous, previousFingerprint == fingerprint {
                return .skipDuplicate
            }
            // ⚠️ 正直に書いておく。絵の中の文字は読めないので、画像には秘密の検知が効かない。
            // パスワードやマイナンバーを写したスクリーンショットは、そうと分からずに残る。
            // だから画像は「設定でまるごと切れる」「残す件数を文字と別枠で少なくする」で受けている。
            return .store

        case .files(let paths):
            if let blocked = blockedBySource(types: types, sourceBundleID: sourceBundleID) { return blocked }
            guard capturesFiles else { return .skipTypeDisabled("ファイル") }
            let cleaned = paths.filter { !$0.trimmingCharacters(in: .whitespaces).isEmpty }
            guard !cleaned.isEmpty else { return .skipEmpty }
            if cleaned.count > ClipboardGuard.maxFileCount { return .skipTooMany(cleaned.count) }
            if case .files(let previousPaths)? = previous, previousPaths == cleaned { return .skipDuplicate }
            // ファイルは中身を持たない（置き場所だけ覚える）。
            // ただし置き場所そのものに秘密が混ざることがあるので、そこは文字と同じように見る。
            let joined = cleaned.joined(separator: "\n")
            for p in userPatterns where !p.isEmpty && joined.localizedCaseInsensitiveContains(p) {
                return .skipSecret(.userPattern(p))
            }
            if let kind = ClipboardGuard.detectSecret(in: joined) { return .skipSecret(kind) }
            return .store
        }
    }

    /// 中身を見る前に決まる分（機密フラグ・除外アプリ）。種類によらず先に効かせる。
    private func blockedBySource(types: [String], sourceBundleID: String?) -> ClipDecision? {
        if let hit = types.first(where: { ClipboardGuard.concealedTypes.contains($0) }) {
            return .skipConcealed(hit)
        }
        if let bundle = sourceBundleID, excludedBundleIDs.contains(bundle) {
            return .skipExcludedApp(bundle)
        }
        return nil
    }

    public func decide(
        types: [String],
        sourceBundleID: String?,
        text: String?,
        byteCount: Int,
        previousText: String?
    ) -> ClipDecision {
        if let hit = types.first(where: { ClipboardGuard.concealedTypes.contains($0) }) {
            return .skipConcealed(hit)
        }
        if let bundle = sourceBundleID, excludedBundleIDs.contains(bundle) {
            return .skipExcludedApp(bundle)
        }
        guard let text, !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return .skipEmpty
        }
        if byteCount > maxBytes {
            return .skipTooLarge(byteCount)
        }
        if let previousText, previousText == text {
            return .skipDuplicate
        }
        for p in userPatterns where !p.isEmpty && text.localizedCaseInsensitiveContains(p) {
            return .skipSecret(.userPattern(p))
        }
        if let kind = ClipboardGuard.detectSecret(in: text) {
            return .skipSecret(kind)
        }
        return .store
    }

    /// 絵から読み取った文字を調べる。
    ///
    /// ⚠️ 判定を `decide` と分けている理由。
    /// 絵は**もう保存されたあと**に読む（読むのに0.3秒かかるので、拾う判断には間に合わない）。
    /// なので「残す／捨てる」ではなく「読んだ文字を持ってよいか」だけを決める。
    /// 自分で足した除外語も、ここで同じように効かせる。
    ///
    /// ⚠️ これが「画像には秘密の検知が効かない」という穴を塞ぐ唯一の場所。
    /// 文字が読めるようになって初めて、スクリーンショットの中のカード番号に気付ける。
    public func detectSecretInImageText(_ text: String) -> SecretKind? {
        for p in userPatterns where !p.isEmpty && text.localizedCaseInsensitiveContains(p) {
            return .userPattern(p)
        }
        return ClipboardGuard.detectSecret(in: text)
    }

    // MARK: - 秘密情報の検知

    /// 接頭辞で判別できるAPIキー類。(接頭辞, 続く英数字の最小長, 表示名)
    private static let keyPrefixes: [(prefix: String, minTail: Int, name: String)] = [
        ("sk-ant-", 20, "Anthropic"),
        ("sk-proj-", 20, "OpenAI"),
        ("sk-", 20, "OpenAI系"),
        ("sk_live_", 16, "Stripe"),
        ("rk_live_", 16, "Stripe"),
        ("github_pat_", 20, "GitHub"),
        ("ghp_", 20, "GitHub"),
        ("gho_", 20, "GitHub"),
        ("ghu_", 20, "GitHub"),
        ("ghs_", 20, "GitHub"),
        ("ghr_", 20, "GitHub"),
        ("xoxb-", 10, "Slack"),
        ("xoxp-", 10, "Slack"),
        ("xoxa-", 10, "Slack"),
        ("xapp-", 10, "Slack"),
        ("AIza", 30, "Google"),
        ("AKIA", 16, "AWS"),
        ("ASIA", 16, "AWS"),
        ("glpat-", 16, "GitLab"),
        ("shpat_", 16, "Shopify"),
        ("npm_", 30, "npm"),
    ]

    public static func detectSecret(in text: String) -> SecretKind? {
        if text.contains("PRIVATE KEY-----") || text.contains("BEGIN OPENSSH PRIVATE KEY") {
            return .privateKey
        }
        if let kind = detectAPIKey(in: text) { return kind }
        if detectJWT(in: text) { return .jwt }
        if let kind = detectSensitiveNumber(in: text) { return kind }
        return nil
    }

    private static func isKeyTailCharacter(_ c: Character) -> Bool {
        c.isLetter && c.isASCII || c.isNumber && c.isASCII || c == "_" || c == "-"
    }

    static func detectAPIKey(in text: String) -> SecretKind? {
        for entry in keyPrefixes {
            var searchStart = text.startIndex
            while let r = text.range(of: entry.prefix, options: [], range: searchStart..<text.endIndex) {
                var tail = 0
                var i = r.upperBound
                while i < text.endIndex, isKeyTailCharacter(text[i]) {
                    tail += 1
                    i = text.index(after: i)
                }
                if tail >= entry.minTail {
                    return .apiKey(entry.name)
                }
                searchStart = r.upperBound
                if searchStart >= text.endIndex { break }
            }
        }
        return nil
    }

    /// JWT: base64url の3つのかたまりがピリオドで繋がり、先頭が eyJ（= {" のbase64）で始まる
    static func detectJWT(in text: String) -> Bool {
        for token in text.split(whereSeparator: { $0.isWhitespace || $0 == "\"" || $0 == "'" }) {
            guard token.hasPrefix("eyJ") else { continue }
            let parts = token.split(separator: ".", omittingEmptySubsequences: false)
            guard parts.count == 3, parts.allSatisfy({ $0.count >= 8 }) else { continue }
            let valid = parts.allSatisfy { part in
                part.allSatisfy { $0.isASCII && ($0.isLetter || $0.isNumber || $0 == "-" || $0 == "_" || $0 == "=") }
            }
            if valid { return true }
        }
        return false
    }

    /// 数字列を取り出してカード番号（Luhn）とマイナンバー（検査用数字）を判定する。
    ///
    /// 区切り記号をまたいで数字を繋げるのは「4桁×4組」の並びに限る。
    /// 単純に空白をまたいで繋げると、取引先コードを並べただけの
    /// 「1000001 1000002」が14桁の1つの数字になり、10回に1回はLuhnを通ってしまう。
    static func detectSensitiveNumber(in text: String) -> SecretKind? {
        for run in digitRuns(in: text) {
            if run.count >= 13 && run.count <= 19 && luhnIsValid(run) {
                return .creditCard
            }
            if run.count == 12 && myNumberIsValid(run) {
                return .myNumber
            }
        }
        for run in groupedCardNumbers(in: text) where luhnIsValid(run) {
            return .creditCard
        }
        return nil
    }

    /// 連続した数字のかたまり（区切り記号はまたがない）
    static func digitRuns(in text: String) -> [[Int]] {
        var runs: [[Int]] = []
        var current: [Int] = []
        for ch in text {
            if ch.isASCII, ch.isNumber, let d = ch.wholeNumberValue {
                current.append(d)
            } else {
                if !current.isEmpty { runs.append(current) }
                current = []
            }
        }
        if !current.isEmpty { runs.append(current) }
        return runs
    }

    /// 「1234-5678-9012-3456」「1234 5678 9012 3456」のように
    /// 4桁が同じ区切り記号で4組並んだものだけを16桁として取り出す。
    static func groupedCardNumbers(in text: String) -> [[Int]] {
        let chars = Array(text)
        var results: [[Int]] = []
        var i = 0

        while i < chars.count {
            guard chars[i].isASCII, chars[i].isNumber else { i += 1; continue }
            // 直前が数字なら、その並びの途中なので開始点にしない
            if i > 0, chars[i - 1].isASCII, chars[i - 1].isNumber { i += 1; continue }

            var digits: [Int] = []
            var cursor = i
            var separator: Character?
            var ok = true

            for group in 0..<4 {
                if group > 0 {
                    guard cursor < chars.count, chars[cursor] == "-" || chars[cursor] == " " else { ok = false; break }
                    if let s = separator, chars[cursor] != s { ok = false; break }
                    separator = chars[cursor]
                    cursor += 1
                }
                var count = 0
                while cursor < chars.count, chars[cursor].isASCII, chars[cursor].isNumber, count < 4 {
                    digits.append(chars[cursor].wholeNumberValue ?? 0)
                    cursor += 1
                    count += 1
                }
                if count != 4 { ok = false; break }
            }
            // 直後にさらに数字が続くなら4桁区切りではない
            if ok, cursor < chars.count, chars[cursor].isASCII, chars[cursor].isNumber { ok = false }

            if ok, digits.count == 16 {
                results.append(digits)
                i = cursor
            } else {
                i += 1
            }
        }
        return results
    }

    /// クレジットカード番号の検査（Luhnアルゴリズム）
    public static func luhnIsValid(_ digits: [Int]) -> Bool {
        guard digits.count >= 13 else { return false }
        var sum = 0
        var double = false
        for d in digits.reversed() {
            var v = d
            if double {
                v *= 2
                if v > 9 { v -= 9 }
            }
            sum += v
            double.toggle()
        }
        return sum % 10 == 0
    }

    /// マイナンバー（個人番号）の検査用数字の判定。
    /// 総務省告示の算式: 下位11桁を P1..P11（右から1始まり）とし
    /// Q(n) = n+1 (1≤n≤6), n-5 (7≤n≤11)、検査用数字 = 11 - (ΣPn×Qn mod 11)。
    /// 結果が10または11のときは0。
    ///
    /// 注意: 検査を通る12桁は約11個に1個あるため、無関係な12桁を誤って弾くことがある。
    /// 「保存しない」側に倒れるだけなので、この誤判定は許容する。
    public static func myNumberIsValid(_ digits: [Int]) -> Bool {
        guard digits.count == 12 else { return false }
        let check = digits[11]
        var sum = 0
        for n in 1...11 {
            let p = digits[11 - n]          // 右から n 番目
            let q = n <= 6 ? n + 1 : n - 5
            sum += p * q
        }
        let r = sum % 11
        let expected = (r <= 1) ? 0 : 11 - r
        return check == expected
    }
}
